# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 15:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.CharField(max_length=200)),
                ('data_diagnosi', models.DateTimeField()),
                ('residenza_paziente', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
