# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 15:50
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandis', '0003_sorgente_poligonale_sorgente_puntiforme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sorgente_lineare',
        ),
        migrations.DeleteModel(
            name='Sorgente_poligonale',
        ),
        migrations.DeleteModel(
            name='Sorgente_puntiforme',
        ),
    ]
