# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 10:13
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mandis', '0005_auto_20171020_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosi',
            name='residenza_paziente',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
    ]
