# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 11:44
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mandis', '0007_auto_20171025_1017'),
    ]

    operations = [
    ]
